name: Release Pipeline

on:
  release:
    types: [ released ]

jobs:
  build:
    name: Deploy Production App
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Image and Tag
        run: >
          docker build -t papiocloudsoftware/github-jenkins .
          && docker tag "papiocloudsoftware/github-jenkins:latest" "papiocloudsoftware/github-jenkins:${RELEASE_VERSION}"

      - name: Docker Login
        run: echo ${{ secrets.DOCKER_HUB }} | docker login -u papiocloud --password-stdin

      - name: Docker Push as Latest
        run: docker push "papiocloudsoftware/github-jenkins:latest"

      - name: Docker Push as Release
        run: docker push "papiocloudsoftware/github-jenkins:${RELEASE_VERSION}"
